name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
  VITE_API_WS_URL: ${{ secrets.VITE_API_WS_URL }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Variables
        run: |
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
        shell: bash

      - name: Build Project Artifacts
        run: |
          # Use environment variables in the build
          echo "VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY" >> .env.production
          echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> .env.production
          echo "VITE_API_WS_URL=$VITE_API_WS_URL" >> .env.production
          vercel build --prod --token=$VERCEL_TOKEN
        shell: bash

      - name: Deploy to Vercel
        run: |
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        shell: bash
